const { google } = require('googleapis');
const fs = require('fs');
const path = require('path');

const CREDENTIALS_PATH = path.join(__dirname, '../../credentials.json');
const TOKEN_PATH = path.join(__dirname, '../../token.json');
const CALLBACK_URL = 'http://localhost:5000/api/v1/google/auth/callback';

const createRealMeetLink = async ({ title, startTime, durationMinutes }) => {
  // Auto-reconnect check
if (!fs.existsSync(TOKEN_PATH)) {
  throw new Error('Google account disconnected. Please reconnect from teacher dashboard.');
}

const tokens = JSON.parse(fs.readFileSync(TOKEN_PATH));

// Warn if token will expire in 7 days
if (tokens.expiry_date) {
  const daysLeft = (tokens.expiry_date - Date.now()) / (1000 * 60 * 60 * 24);
  if (daysLeft < 7) {
    console.warn(`⚠️ Google token expires in ${Math.round(daysLeft)} days`);
  }
}
  if (!fs.existsSync(CREDENTIALS_PATH)) {
    throw new Error('credentials.json not found');
  }

  if (!fs.existsSync(TOKEN_PATH)) {
    throw new Error('Google account not connected. Teacher must connect Google account first.');
  }

  const creds = JSON.parse(fs.readFileSync(CREDENTIALS_PATH));
  const { client_id, client_secret } = creds.installed || creds.web;
  const oauth2Client = new google.auth.OAuth2(client_id, client_secret, CALLBACK_URL);

  const tokens = JSON.parse(fs.readFileSync(TOKEN_PATH));
  oauth2Client.setCredentials(tokens);

  oauth2Client.on('tokens', (newTokens) => {
    const updated = { ...tokens, ...newTokens };
    fs.writeFileSync(TOKEN_PATH, JSON.stringify(updated));
    console.log('Token refreshed and saved');
  });

  const calendar = google.calendar({ version: 'v3', auth: oauth2Client });

  const endTime = new Date(startTime);
  endTime.setMinutes(endTime.getMinutes() + (durationMinutes || 60));

  const event = {
    summary: title,
    description: 'Smart LMS Live Class — Auto generated by Smart LMS',
    start: {
      dateTime: new Date(startTime).toISOString(),
      timeZone: 'Asia/Kathmandu',
    },
    end: {
      dateTime: endTime.toISOString(),
      timeZone: 'Asia/Kathmandu',
    },
    conferenceData: {
      createRequest: {
        requestId: `lms-${Date.now()}`,
        conferenceSolutionKey: { type: 'hangoutsMeet' },
      },
    },
  };

  const response = await calendar.events.insert({
    calendarId: 'primary',
    resource: event,
    conferenceDataVersion: 1,
  });

  const meetLink =
    response.data.hangoutLink ||
    response.data.conferenceData?.entryPoints?.find(
      (ep) => ep.entryPointType === 'video'
    )?.uri;

  console.log(`✅ Real Meet link: ${meetLink}`);
  console.log(`📅 Calendar: ${response.data.htmlLink}`);

  return {
    meetLink,
    eventId: response.data.id,
    htmlLink: response.data.htmlLink,
  };
};

module.exports = { createRealMeetLink };